### ISSUE TITLE
New Public Repo, it has just the necesary files to reproduce the analysis 

### ISSUE THREAD

**Issue by MaC-Perez** [MaC-Perez/BSB_PP#1]
Hi @apain23 @samtruesdell  

I created a new public repo containing only the necessary files to reproduce the analysis. I modified the R code and changed the model names to make them more intuitive (since before we had mod 1, mod2, ..... mod 220000). 

Could you please run the code and check if everything is working propoerly? also I had some difficulties here https://github.com/MaC-Perez/BSB_PP/blob/a928b0b50a0cac0f72a833e25582a00c4ba3c624/CPUE/CPUE_BSB_final.R#L281
because the BB data doesnt have the year 2013 so the plot doesnt have that number. @samtruesdell any chance you could help me to add an extra data point in that data frame  (2013 with an NA)

**Comment by struesdell** [comment]
I think I got 2013 to be what you're going for (73817e38ae5173c4644c0c249b436e19156a722a). When I run the full code (CPUE_BSB_final) I've still got one problem ... the first reference to newdat seems to be line 447 but it's not declared there. Should I be running something before CPUE_BSB_final?

**Comment by MaC-Perez** [comment]
thanks @samtruesdell !!!! I was able to plot the 2013 

regarding the newdata problem...I am still trying to rememeber how we did that. I am working on that now. Ill keep you updated
