### ISSUE TITLE
Negative initial value 

### ISSUE THREAD

**Issue by MaC-Perez** [MaC-Perez/BSB_PP#2]
@apain23 @samtruesdell 
also the negative binomial model for RI (unvented) is estimating negative values for the first coefficient. I dont know if that's normal or I am extracting the coefficients wrong

https://github.com/MaC-Perez/BSB_PP/blob/a928b0b50a0cac0f72a833e25582a00c4ba3c624/CPUE/CPUE_BSB_final.R#L310

**Comment by struesdell** [comment]
My initial thought is that the coefficients from the NB model would be on the scale of the linear predictor so you might want to exponentiate them if you want to call the coefficients the index. That's suitable, but what I've done in the past is to use predict(scale = response) where newdata is a list of year factors and the most common values for the other coefficients (e.g., depth). I've got some meetings this afternoon but happy to chat about this and figure it out. Thanks for cleaning up the code!

**Comment by MaC-Perez** [comment]
@samtruesdell  yep, I that for the negbin models but I am having the problem here...

BBv <- glm(bsbCount_Vented ~ as.factor(Year) + as.factor(Month)+ as.factor(depthStrata), family = "poisson", 
            data = BB, offset(trapCount_Vented))
what else should I check?

**Comment by MaC-Perez** [comment]
thanks @samtruesdell !!! I did that in the excel but I forgot to add (exp) in the R code
