### ISSUE TITLE
x axis in prediction plots 

### ISSUE THREAD

**Issue by MaC-Perez** [MaC-Perez/BSB_PP#4]
@samtruesdell ... could you please check the x axis in these two plots? 

https://github.com/MaC-Perez/BSB_PP/blob/deb311c0d20284e4295c7c95905ac3552b276c0b/CPUE/CPUE_BSB_final.R#L479

https://github.com/MaC-Perez/BSB_PP/blob/deb311c0d20284e4295c7c95905ac3552b276c0b/CPUE/CPUE_BSB_final.R#L539

**Comment by struesdell** [comment]
I think these are fixed up -- let me know if you were thinking of something else

**Comment by MaC-Perez** [comment]
@samtruesdell working now!!! thanks Sam!
